test_app/config/routes.rb
TestApp::Application.routes.draw do
  resources :landscapes do
    post 'crop', :on => :member
  end

  root :to => 'landscapes#index'
end

test_app/app/models/landscape.rb
class Landscape < ActiveRecord::Base

  has_attached_file  :picture, :styles => {:thumb => "40x30", :medium => "400x300"},
                               :path   => ":rails_root/public/assets/uploads/landscapes/:id_:style.:extension",
                               :url    => "/assets/uploads/landscapes/:id_:style.:extension"
  validates_attachment_content_type :picture, :content_type => /.*/
  crop_attached_file :picture, :aspect => "4:3"

end

test_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

test_app/app/controllers/landscapes_controller.rb
class LandscapesController < ApplicationController
  # GET /landscapes
  # GET /landscapes.json
  def index
    @landscapes = Landscape.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @landscapes }
    end
  end

  # GET /landscapes/1
  # GET /landscapes/1.json
  def show
    @landscape = Landscape.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @landscape }
    end
  end

  # GET /landscapes/new
  # GET /landscapes/new.json
  def new
    @landscape = Landscape.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @landscape }
    end
  end

  # GET /landscapes/1/edit
  def edit
    @landscape = Landscape.find(params[:id])
  end

  # POST /landscapes
  # POST /landscapes.json
  def create
    @landscape = Landscape.new(landscape_params)

    respond_to do |format|
      if @landscape.save
        format.html { render 'crop' }
        format.json { render json: @landscape, status: :created, location: @landscape }
      else
        format.html { render action: "new" }
        format.json { render json: @landscape.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /landscapes/1
  # PUT /landscapes/1.json
  def update
    @landscape = Landscape.find(params[:id])

    respond_to do |format|
      if @landscape.update_attributes(landscape_params)
        format.html { redirect_to @landscape, notice: 'Landscape was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @landscape.errors, status: :unprocessable_entity }
      end
    end
  end


  # POST /landscapes/1/crop
  # POST /landscapes/1/crop.json
  def crop
    @landscape = Landscape.find(params[:id])
  end


  # DELETE /landscapes/1
  # DELETE /landscapes/1.json
  def destroy
    @landscape = Landscape.find(params[:id])
    @landscape.destroy

    respond_to do |format|
      format.html { redirect_to landscapes_url }
      format.json { head :no_content }
    end
  end

private

  def landscape_params
    params.fetch(:landscape, {}).permit!
  end

end

test_app/app/helpers/application_helper.rb
module ApplicationHelper
end

test_app/app/views/landscapes/_crop_form.html.erb
<%= form_for(@landscape) do |f| %>
  
  <div class="landscape-crop-preview">
    <% # Will show a preview box with width=100, height is calculated by the aspect ratio. see model Landscape %>
    <%= f.crop_preview :picture %>
  </div>
  <div class="landscape-crop-area">
    <% # Crop area. Mantains original image proportions. Crop area takes the aspect ratio  %>
    <%= f.cropbox :picture, :width => 600 %>
  </div>
  <div class="clear"></div>

  <div class="actions">
    <%= f.submit 'Crop image' %>
  </div>
<% end %>

test_app/app/views/landscapes/_form.html.erb
<%= form_for(@landscape) do |f| %>
  <% if @landscape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@landscape.errors.count, "error") %> prohibited this landscape from being saved:</h2>

      <ul>
      <% @landscape.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>

test_app/app/views/landscapes/crop.html.erb
<%= render "crop_form" %>

test_app/app/views/landscapes/crop.js.erb
$('body').html($('<%= escape_javascript(render("crop_form"))%>'));
init_papercrop();

test_app/app/views/landscapes/edit.html.erb
<h1>Editing landscape</h1>

<%= render 'form' %>

<%= link_to 'Show', @landscape %> |
<%= link_to 'Back', landscapes_path %>

test_app/app/views/landscapes/index.html.erb
<h1>Listing landscapes</h1>

<table>
  <tr>
    <th>Picture</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @landscapes.each do |landscape| %>
  <tr>
    <td><%= image_tag landscape.picture(:thumb) %></td>
    <td><%= landscape.name %></td>
    <td><%= link_to 'Show', landscape %></td>
    <td><%= link_to 'Edit', edit_landscape_path(landscape) %></td>
    <td><%= link_to 'Crop', crop_landscape_path(landscape), :remote => true, :method => :post %></td>
    <td><%= link_to 'Destroy', landscape, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Landscape', new_landscape_path %>

test_app/app/views/landscapes/new.html.erb
<h1>New landscape</h1>

<%= render 'form' %>

<%= link_to 'Back', landscapes_path %>

test_app/app/views/landscapes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @landscape.name %>
</p>

<%= image_tag @landscape.picture(:medium) %>

<br />

<%= link_to 'Edit', edit_landscape_path(@landscape) %> |
<%= link_to 'Back', landscapes_path %>

test_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>